"""The code-quality ratchet must catch every direction of drift.

A frozen baseline is only worth committing if it actually fails when debt
grows. Each test below reproduces one way the ratchet can rot -- a new
oversized module, an existing one growing, an improvement nobody wrote back,
a stale entry for a file that is now fine -- and asserts the gate notices.

Contract: ``docs/design/code-quality-contract.md``.
"""

from __future__ import annotations

import json

import pytest

from tests.casefiles import case_values

from slm_training.quality import baseline, gate
from slm_training.quality.sources import (
    MAX_MODULE_LINES,
    SourceFile,
    is_excluded,
    is_generated,
    over_budget,
)


def _compare(current: dict[str, int], recorded: dict[str, int]):
    return baseline.compare(
        current, recorded, dimension="module_lines", unit="lines"
    )


def test_unchanged_debt_is_clean() -> None:
    outcome = _compare({"a.py": 500}, {"a.py": 500})
    assert outcome.clean
    assert not outcome.failures


def test_growth_is_a_regression() -> None:
    outcome = _compare({"a.py": 620}, {"a.py": 500})
    assert outcome.regressions == [
        "a.py: module_lines grew 500 -> 620 lines (+120)"
    ]
    assert outcome.failures


def test_new_violation_without_a_baseline_entry_fails() -> None:
    outcome = _compare({"b.py": 401}, {})
    assert outcome.unlisted == ["b.py: new module_lines violation (401 lines)"]
    assert outcome.failures


def test_unrecorded_improvement_is_drift_not_failure() -> None:
    """Shrinking a file must force the ceiling down, so the win is permanent."""

    outcome = _compare({"a.py": 450}, {"a.py": 500})
    assert not outcome.failures
    assert outcome.improvements == [
        "a.py: improved 500 -> 450 lines; lower the baseline"
    ]
    assert not outcome.clean


def test_entry_for_a_now_compliant_file_is_stale() -> None:
    outcome = _compare({}, {"a.py": 500})
    assert not outcome.failures
    assert outcome.stale == [
        "a.py: no longer violates module_lines; drop the baseline entry"
    ]


def test_over_budget_ranks_worst_first() -> None:
    files = [
        SourceFile(path="small.py", lines=10, language="python"),
        SourceFile(path="big.py", lines=900, language="python"),
        SourceFile(path="mid.py", lines=401, language="python"),
    ]
    assert [item.path for item in over_budget(files)] == ["big.py", "mid.py"]


def test_budget_boundary_is_inclusive() -> None:
    at_budget = SourceFile(path="x.py", lines=MAX_MODULE_LINES, language="python")
    over = SourceFile(path="y.py", lines=MAX_MODULE_LINES + 1, language="python")
    assert not at_budget.over_budget
    assert over.over_budget


@pytest.mark.parametrize(
    "path",
    case_values(__file__, "test_build_output_and_vendored_trees_are_excluded"),
)
def test_build_output_and_vendored_trees_are_excluded(path: str) -> None:
    """A budget levied on generated bytes measures the generator, not us."""

    assert is_excluded(path)


def test_repo_owned_source_is_not_excluded() -> None:
    assert not is_excluded("src/slm_training/quality/gate.py")


def test_generated_headers_are_skipped() -> None:
    assert is_generated("# @generated by protoc\nx = 1\n")
    assert not is_generated('"""A hand-written module."""\nx = 1\n')


def test_baseline_rejects_an_unknown_schema(tmp_path) -> None:
    target = tmp_path / "src/slm_training/resources/code_quality_baseline.json"
    target.parent.mkdir(parents=True)
    target.write_text(json.dumps({"schema": "something_else/v9"}))
    with pytest.raises(ValueError, match="expected schema"):
        baseline.load(root=tmp_path)


def test_baseline_round_trips(tmp_path) -> None:
    baseline.save({"module_lines": {"b.py": 2, "a.py": 1}}, root=tmp_path)
    loaded = baseline.load(root=tmp_path)
    assert loaded["schema"] == baseline.SCHEMA
    assert baseline.dimension(loaded, "module_lines") == {"a.py": 1, "b.py": 2}
    # Deterministic ordering keeps the committed diff reviewable.
    assert list(baseline.dimension(loaded, "module_lines")) == ["a.py", "b.py"]


def test_missing_baseline_loads_empty(tmp_path) -> None:
    assert baseline.load(root=tmp_path) == {}

def test_non_source_trees_are_excluded_from_the_filesystem_fallback() -> None:
    """Without this the git-less fallback would record `.venv` as our debt."""

    for path in (
        ".venv/lib/python3.12/site-packages/numpy/core.py",
        "outputs/run-2026/scratch.py",
        "build/lib/thing.py",
        ".ruff_cache/x.py",
    ):
        assert is_excluded(path), path


def test_nested_caches_and_vendor_dirs_are_excluded_at_any_depth() -> None:
    assert is_excluded("src/slm_training/__pycache__/gate.cpython-312.py")
    assert is_excluded("src/apps/dashboard/node_modules/react/index.ts")


def test_tooling_versions_round_trip(tmp_path) -> None:
    baseline.save({}, root=tmp_path, tools={"ruff": "ruff 0.15.22"})
    assert baseline.tooling(baseline.load(root=tmp_path)) == {"ruff": "ruff 0.15.22"}


def test_missing_tooling_block_reads_empty(tmp_path) -> None:
    baseline.save({}, root=tmp_path)
    assert baseline.tooling(baseline.load(root=tmp_path)) == {}


def test_tooling_drift_is_reported_only_when_the_version_actually_moved() -> None:
    """A ruff bump moves many counts at once; say so instead of calling it
    hundreds of code regressions."""

    report = _report(ruff_version="ruff 0.16.0")
    assert gate.tooling_drift(report, {"tooling": {"ruff": "ruff 0.15.22"}})
    assert gate.tooling_drift(report, {"tooling": {"ruff": "ruff 0.16.0"}}) is None
    assert gate.tooling_drift(report, {}) is None
    assert gate.tooling_drift(_report(ruff_version=None), {"tooling": {"ruff": "x"}}) is None


def _report(*, ruff_version: str | None) -> gate.QualityReport:
    return gate.QualityReport(
        files=[],
        oversized=[],
        complexity=[],
        components=[],
        edges={},
        cycles=[],
        sdp=[],
        sap=[],
        ruff_version=ruff_version,
    )
