"""SRP-008 (SLM-471): deterministic symbolic-regression corpus generation
with topology-family train/eval separation and frozen OOD slices.

Composes rather than re-derives: canonical form comes from
``symbolic_expr_canonicalize.canonicalize_expr``, complexity from
``symbolic_expr_ir.expr_depth_and_node_count``, numeric evaluation from
``symbolic_expr_evaluator.evaluate_vectorized``, and the corpus-level
train/validation/test split assignment reuses
``harnesses.train_data.split_policy.RootFamilySplitPolicyV1`` -- the same
deterministic, hash-bucketed "structural family decides split, before any
numeric sampling" policy already used for the OpenUI training corpus,
applied here with a canonical symbolic-expression hash as the family id.

Leakage/dedup auditing over a generated corpus runs through the existing
``data_corpus_audit`` tool (``scripts/audit_data_corpora.py``,
``symbolic_regression_corpus_leakage_report`` / ``--mode
symbolic-regression-audit``) per AGENTS.md's data-quality law and this
subsystem's own design-doc note ("New corpora ... run through this existing
tool rather than a new leakage checker"); that CLI wrapper calls
:func:`generate_corpus` and :func:`audit_corpus_leakage` directly rather than
reimplementing family/topology leakage detection a second time.

Coefficient placement is guaranteed affine by construction (each generated
expression is either a pure coefficient-free basis tree, or
``sum_i(c_i * basis_i(vars)) + c_offset`` for independently sampled
coefficient-free ``basis_i``) -- this is the same shape SRP-004's
``fit_least_squares`` already supports. Independently-sampled basis terms
can still coincide (e.g. two terms both reducing to plain ``x0``), making
their combined coefficients non-identifiable from data alone; a candidate is
fit against its own true coefficients at generation time and rejected as
``collinear_coefficient_terms`` if that fit is rank-deficient, so every
surviving coefficient-bearing corpus record has its true coefficients
guaranteed exactly recoverable, not merely guaranteed fittable.

The true canonical equation and true coefficients are oracle-only
(:class:`CorpusOracleV1`) and never populate any field of the generated
:class:`SymbolicRegressionProblemV1` (its ``provenance`` is always left
empty) -- nothing that resembles a model-visible prompt is generated by this
module at all, so there is no other surface for the answer to leak through.
"""

from __future__ import annotations

import hashlib
import json
import random
from dataclasses import asdict, dataclass, field
from typing import Any

import numpy as np

from slm_training.dsl.symbolic_expr_canonicalize import canonicalize_expr
from slm_training.dsl.symbolic_expr_evaluator import (
    DEFAULT_DOMAIN_POLICY,
    NUMERIC_DOMAIN_POLICIES,
    evaluate_vectorized,
)
from slm_training.dsl.symbolic_expr_fit import fit_least_squares
from slm_training.dsl.symbolic_expr_ir import (
    BINARY_OPERATORS,
    UNARY_OPERATORS,
    CoefficientHole,
    OpApply,
    SymbolicExprNode,
    VarRef,
    collect_symbols,
    expr_depth_and_node_count,
    serialize_expr,
)
from slm_training.dsl.symbolic_regression_pack import (
    ALLOWED_OPERATORS,
    SymbolicRegressionProblemV1,
)
from slm_training.harnesses.train_data.split_policy import SPLITS, RootFamilySplitPolicyV1

CORPUS_SCHEMA_VERSION = "v1"

REJECTION_REASONS = frozenset(
    {
        "constant_expression",
        "over_budget",
        "duplicate_family",
        "degenerate_numeric_domain",
        "degenerate_constant_targets",
        "collinear_coefficient_terms",
    }
)

_MAX_ATTEMPTS_MULTIPLIER = 25
_MIN_COEFFICIENT_MAGNITUDE = 0.25
_LEAF_PROBABILITY = 0.4
_COEFFICIENT_REGIME_SMALL = 1.0
_COEFFICIENT_REGIME_LARGE = 3.0


def _digest(value: Any) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class CorpusGenerationConfigV1:
    """Declared operator/depth/node/domain distributions for one corpus build."""

    schema_version: str
    seed: int
    num_problems: int
    num_variables_range: tuple[int, int]
    allowed_operators: frozenset[str]
    max_basis_depth: int
    max_coefficient_terms: int
    coefficient_probability: float
    numeric_domain_policy: str
    complexity_budget: int
    train_rows: int
    validation_rows: int
    extrapolation_rows: int
    train_domain: tuple[float, float]
    extrapolation_domain: tuple[float, float]
    coefficient_range: tuple[float, float]
    split_policy: RootFamilySplitPolicyV1 = field(default_factory=RootFamilySplitPolicyV1)

    def __post_init__(self) -> None:
        if self.schema_version != CORPUS_SCHEMA_VERSION:
            raise ValueError(f"unsupported corpus config schema: {self.schema_version!r}")
        if self.seed < 0:
            raise ValueError("seed must be non-negative")
        if self.num_problems <= 0:
            raise ValueError("num_problems must be positive")
        lo, hi = self.num_variables_range
        if lo < 1 or hi < lo:
            raise ValueError(f"invalid num_variables_range: {self.num_variables_range!r}")
        if not self.allowed_operators or self.allowed_operators - ALLOWED_OPERATORS:
            raise ValueError(f"allowed_operators must be a non-empty subset of {sorted(ALLOWED_OPERATORS)}")
        if self.max_basis_depth <= 0:
            raise ValueError("max_basis_depth must be positive")
        if self.max_coefficient_terms < 1:
            raise ValueError("max_coefficient_terms must be at least 1")
        if not 0.0 <= self.coefficient_probability <= 1.0:
            raise ValueError("coefficient_probability must be within [0, 1]")
        if self.numeric_domain_policy not in NUMERIC_DOMAIN_POLICIES:
            raise ValueError(f"unsupported numeric_domain_policy: {self.numeric_domain_policy!r}")
        if self.complexity_budget <= 0:
            raise ValueError("complexity_budget must be positive")
        if self.train_rows <= 0 or self.validation_rows <= 0 or self.extrapolation_rows < 0:
            raise ValueError("train_rows/validation_rows must be positive, extrapolation_rows non-negative")
        if self.train_domain[0] >= self.train_domain[1]:
            raise ValueError("train_domain must be an increasing (lo, hi) pair")
        if self.extrapolation_domain[0] >= self.extrapolation_domain[1]:
            raise ValueError("extrapolation_domain must be an increasing (lo, hi) pair")
        if self.extrapolation_domain[0] < self.train_domain[1] and self.extrapolation_domain[1] > self.train_domain[0]:
            raise ValueError("extrapolation_domain must not overlap train_domain")
        if self.coefficient_range[0] >= self.coefficient_range[1]:
            raise ValueError("coefficient_range must be an increasing (lo, hi) pair")


@dataclass(frozen=True)
class CorpusOracleV1:
    """Oracle-only ground truth: the true equation and coefficients. Never
    copied into any field of the generated ``SymbolicRegressionProblemV1``."""

    schema_version: str
    canonical_expr: str
    true_coefficients: tuple[float, ...]
    family_id: str
    operator_signature: frozenset[str]

    def __post_init__(self) -> None:
        if self.schema_version != CORPUS_SCHEMA_VERSION:
            raise ValueError(f"unsupported oracle schema: {self.schema_version!r}")
        if hashlib.sha256(self.canonical_expr.encode("utf-8")).hexdigest() != self.family_id:
            raise ValueError("family_id does not match sha256(canonical_expr)")

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "canonical_expr": self.canonical_expr,
            "true_coefficients": list(self.true_coefficients),
            "family_id": self.family_id,
            "operator_signature": sorted(self.operator_signature),
        }


@dataclass(frozen=True)
class CorpusRecordV1:
    """One generated symbolic-regression problem plus its oracle-only truth."""

    schema_version: str
    family_id: str
    corpus_split: str
    problem: SymbolicRegressionProblemV1
    oracle: CorpusOracleV1

    def __post_init__(self) -> None:
        if self.schema_version != CORPUS_SCHEMA_VERSION:
            raise ValueError(f"unsupported record schema: {self.schema_version!r}")
        if self.corpus_split not in SPLITS:
            raise ValueError(f"unsupported corpus_split: {self.corpus_split!r}")
        if self.family_id != self.oracle.family_id:
            raise ValueError("record family_id does not match oracle.family_id")


@dataclass(frozen=True)
class CorpusRejectionV1:
    """One generation candidate that was filtered out, with a recorded reason."""

    reason: str
    detail: str

    def __post_init__(self) -> None:
        if self.reason not in REJECTION_REASONS:
            raise ValueError(f"unsupported rejection reason: {self.reason!r}")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class CorpusOodSlicesV1:
    """Frozen, named, reproducible out-of-distribution slices over the
    non-train records of one corpus."""

    schema_version: str
    unseen_topology: tuple[str, ...]
    unseen_operator_composition: tuple[str, ...]
    unseen_variable_dimensionality: tuple[str, ...]
    unseen_coefficient_regime: tuple[str, ...]

    def __post_init__(self) -> None:
        if self.schema_version != CORPUS_SCHEMA_VERSION:
            raise ValueError(f"unsupported OOD slice schema: {self.schema_version!r}")
        for name in (
            "unseen_topology",
            "unseen_operator_composition",
            "unseen_variable_dimensionality",
            "unseen_coefficient_regime",
        ):
            value = getattr(self, name)
            if tuple(sorted(value)) != value:
                raise ValueError(f"{name} must be sorted")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class SymbolicRegressionCorpusV1:
    """A full generated corpus: records, recorded rejections, OOD slices,
    and a content fingerprint proving seed/config reproducibility."""

    schema_version: str
    seed: int
    records: tuple[CorpusRecordV1, ...]
    rejections: tuple[CorpusRejectionV1, ...]
    ood_slices: CorpusOodSlicesV1
    corpus_fingerprint: str

    def __post_init__(self) -> None:
        if self.schema_version != CORPUS_SCHEMA_VERSION:
            raise ValueError(f"unsupported corpus schema: {self.schema_version!r}")
        if not self.records:
            raise ValueError("records must be non-empty")
        family_ids = [r.family_id for r in self.records]
        if len(set(family_ids)) != len(family_ids):
            raise ValueError("records must not repeat a family_id")


@dataclass(frozen=True)
class CorpusLeakageAuditV1:
    """Leakage/dedup audit result over a generated corpus."""

    schema_version: str
    cross_split_family_violations: tuple[str, ...]
    duplicate_family_ids: tuple[str, ...]
    is_clean: bool

    def __post_init__(self) -> None:
        if self.schema_version != CORPUS_SCHEMA_VERSION:
            raise ValueError(f"unsupported audit schema: {self.schema_version!r}")
        expected_clean = not self.cross_split_family_violations and not self.duplicate_family_ids
        if self.is_clean != expected_clean:
            raise ValueError("is_clean is inconsistent with the recorded violations")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _sample_basis_tree(
    rng: random.Random, *, num_variables: int, max_depth: int, allowed_operators: frozenset[str]
) -> SymbolicExprNode:
    """A coefficient-free (pure-variable) subtree -- always affine-safe as a
    multiplicative/offset factor since it carries no coefficient hole."""
    if max_depth <= 0 or rng.random() < _LEAF_PROBABILITY:
        return VarRef(index=rng.randrange(num_variables))
    binary_ops = sorted(BINARY_OPERATORS & allowed_operators)
    unary_ops = sorted(UNARY_OPERATORS & allowed_operators)
    choices = binary_ops + unary_ops
    if not choices:
        return VarRef(index=rng.randrange(num_variables))
    operator = rng.choice(choices)
    child_kwargs = dict(num_variables=num_variables, max_depth=max_depth - 1, allowed_operators=allowed_operators)
    if operator in BINARY_OPERATORS:
        return OpApply(
            operator=operator,
            args=(_sample_basis_tree(rng, **child_kwargs), _sample_basis_tree(rng, **child_kwargs)),
        )
    return OpApply(operator=operator, args=(_sample_basis_tree(rng, **child_kwargs),))


def _sample_affine_tree(
    rng: random.Random, *, num_variables: int, config: CorpusGenerationConfigV1
) -> tuple[SymbolicExprNode, int]:
    """``sum_i(c_i * basis_i(vars)) + c_offset`` -- guaranteed affine in its
    coefficient holes by construction (mirrors SRP-004/SRP-006's
    coefficient-free-factor * basis pattern)."""
    num_terms = rng.randint(1, config.max_coefficient_terms)
    terms: list[SymbolicExprNode] = []
    for index in range(num_terms):
        basis = _sample_basis_tree(
            rng, num_variables=num_variables, max_depth=config.max_basis_depth, allowed_operators=config.allowed_operators
        )
        terms.append(OpApply(operator="*", args=(CoefficientHole(index=index), basis)))
    terms.append(CoefficientHole(index=num_terms))
    tree = terms[0]
    for term in terms[1:]:
        tree = OpApply(operator="+", args=(tree, term))
    return tree, num_terms + 1


def _sample_coefficient_values(rng: random.Random, count: int, coefficient_range: tuple[float, float]) -> tuple[float, ...]:
    lo, hi = coefficient_range
    values: list[float] = []
    for _ in range(count):
        value = rng.uniform(lo, hi)
        attempts = 0
        while abs(value) < _MIN_COEFFICIENT_MAGNITUDE and attempts < 10:
            value = rng.uniform(lo, hi)
            attempts += 1
        values.append(value)
    return tuple(values)


def _operator_names(node: SymbolicExprNode) -> frozenset[str]:
    names: set[str] = set()

    def walk(current: SymbolicExprNode) -> None:
        if isinstance(current, OpApply):
            names.add(current.operator)
            for arg in current.args:
                walk(arg)

    walk(node)
    return frozenset(names)


def _coefficient_regime(value: float) -> str:
    magnitude = abs(value)
    if magnitude < _COEFFICIENT_REGIME_SMALL:
        return "small"
    if magnitude < _COEFFICIENT_REGIME_LARGE:
        return "medium"
    return "large"


def _coefficient_regimes(record: CorpusRecordV1) -> frozenset[str]:
    return frozenset(_coefficient_regime(value) for value in record.oracle.true_coefficients)


def _build_ood_slices(records: tuple[CorpusRecordV1, ...]) -> CorpusOodSlicesV1:
    train_records = tuple(r for r in records if r.corpus_split == "train")
    train_family_ids = frozenset(r.family_id for r in train_records)
    train_operator_signatures = frozenset(r.oracle.operator_signature for r in train_records)
    train_variable_dims = frozenset(len(r.problem.variables) for r in train_records)
    train_coefficient_regimes: frozenset[str] = frozenset().union(
        *(_coefficient_regimes(r) for r in train_records)
    ) if train_records else frozenset()

    non_train_family_ids = tuple(sorted(r.family_id for r in records if r.family_id not in train_family_ids))
    unseen_operator_composition = tuple(
        sorted(
            r.family_id
            for r in records
            if r.family_id not in train_family_ids and r.oracle.operator_signature not in train_operator_signatures
        )
    )
    unseen_variable_dimensionality = tuple(
        sorted(
            r.family_id
            for r in records
            if r.family_id not in train_family_ids and len(r.problem.variables) not in train_variable_dims
        )
    )
    unseen_coefficient_regime = tuple(
        sorted(
            r.family_id
            for r in records
            if r.family_id not in train_family_ids and not (_coefficient_regimes(r) <= train_coefficient_regimes)
        )
    )
    return CorpusOodSlicesV1(
        schema_version=CORPUS_SCHEMA_VERSION,
        unseen_topology=non_train_family_ids,
        unseen_operator_composition=unseen_operator_composition,
        unseen_variable_dimensionality=unseen_variable_dimensionality,
        unseen_coefficient_regime=unseen_coefficient_regime,
    )


def _corpus_fingerprint(seed: int, records: tuple[CorpusRecordV1, ...]) -> str:
    payload = {
        "seed": seed,
        "records": [
            {
                "family_id": r.family_id,
                "corpus_split": r.corpus_split,
                "problem_fingerprint": r.problem.fingerprint,
                "oracle": r.oracle.to_dict(),
            }
            for r in sorted(records, key=lambda record: record.family_id)
        ],
    }
    return _digest(payload)


def generate_corpus(config: CorpusGenerationConfigV1) -> SymbolicRegressionCorpusV1:
    """Deterministically generate ``config.num_problems`` corpus records.

    Canonical expression families are assigned to a corpus split (via
    ``config.split_policy``) before any numeric row is sampled, so two
    canonically-equivalent expressions can never land in different splits.
    Every generated dataset is fully numerically valid and non-constant;
    candidates that are not are filtered with a recorded reason rather than
    silently dropped or repaired. Raises if the requested problem count
    cannot be reached within a bounded number of attempts, rather than
    silently returning a smaller corpus.
    """
    rng = random.Random(config.seed)
    records: list[CorpusRecordV1] = []
    rejections: list[CorpusRejectionV1] = []
    seen_family_ids: set[str] = set()
    max_attempts = config.num_problems * _MAX_ATTEMPTS_MULTIPLIER
    attempts = 0

    while len(records) < config.num_problems and attempts < max_attempts:
        attempts += 1
        num_variables = rng.randint(*config.num_variables_range)
        if rng.random() < config.coefficient_probability:
            tree, num_coefficients = _sample_affine_tree(rng, num_variables=num_variables, config=config)
        else:
            tree = _sample_basis_tree(
                rng, num_variables=num_variables, max_depth=config.max_basis_depth, allowed_operators=config.allowed_operators
            )
            num_coefficients = 0

        variable_indices, _coefficient_indices = collect_symbols(tree)
        if not variable_indices:
            rejections.append(CorpusRejectionV1(reason="constant_expression", detail=serialize_expr(tree)))
            continue
        _depth, node_count = expr_depth_and_node_count(tree)
        if node_count > config.complexity_budget:
            rejections.append(CorpusRejectionV1(reason="over_budget", detail=f"node_count={node_count}"))
            continue

        canonical_expr = serialize_expr(canonicalize_expr(tree))
        family_id = hashlib.sha256(canonical_expr.encode("utf-8")).hexdigest()
        if family_id in seen_family_ids:
            rejections.append(CorpusRejectionV1(reason="duplicate_family", detail=family_id))
            continue

        true_coefficients = _sample_coefficient_values(rng, num_coefficients, config.coefficient_range)
        coefficients_arr = np.array(true_coefficients, dtype=np.float64) if num_coefficients else None

        train_rows = [[rng.uniform(*config.train_domain) for _ in range(num_variables)] for _ in range(config.train_rows)]
        validation_rows = [
            [rng.uniform(*config.train_domain) for _ in range(num_variables)] for _ in range(config.validation_rows)
        ]
        extrapolation_rows = [
            [rng.uniform(*config.extrapolation_domain) for _ in range(num_variables)]
            for _ in range(config.extrapolation_rows)
        ]
        table_rows = train_rows + validation_rows + extrapolation_rows
        variables_arr = np.array(table_rows, dtype=np.float64)
        train_indices = tuple(range(0, len(train_rows)))
        validation_indices = tuple(range(len(train_rows), len(train_rows) + len(validation_rows)))
        extrapolation_indices = tuple(range(len(train_rows) + len(validation_rows), len(table_rows)))

        result = evaluate_vectorized(
            tree, variables=variables_arr, coefficients=coefficients_arr, domain_policy=config.numeric_domain_policy
        )
        if result.failure_class != "none":
            rejections.append(CorpusRejectionV1(reason="degenerate_numeric_domain", detail=family_id))
            continue
        targets = tuple(result.predictions)
        if float(np.ptp(np.array(targets))) < 1e-9:
            rejections.append(CorpusRejectionV1(reason="degenerate_constant_targets", detail=family_id))
            continue

        if num_coefficients:
            # Independently-sampled basis terms can coincide, making their
            # combined coefficients non-identifiable from data alone -- fit
            # against the true (noise-free) targets and reject collinear
            # designs so every surviving record's coefficients are exactly
            # recoverable, not merely fittable.
            train_fit = fit_least_squares(
                tree,
                variables=variables_arr,
                targets=np.array(targets, dtype=np.float64),
                train_indices=np.array(train_indices, dtype=np.intp),
                domain_policy=config.numeric_domain_policy,
            )
            if train_fit.is_rank_deficient:
                rejections.append(CorpusRejectionV1(reason="collinear_coefficient_terms", detail=family_id))
                continue

        problem = SymbolicRegressionProblemV1(
            variables=tuple(f"x{i}" for i in range(num_variables)),
            table=tuple(tuple(row) for row in table_rows),
            targets=targets,
            allowed_operators=config.allowed_operators,
            coefficient_hole_policy=("fit_free_coefficients" if num_coefficients else "fixed_constants_only"),
            complexity_budget=config.complexity_budget,
            numeric_domain_policy=config.numeric_domain_policy,
            train_indices=train_indices,
            validation_indices=validation_indices,
            extrapolation_indices=extrapolation_indices,
            seed=config.seed,
        )
        oracle = CorpusOracleV1(
            schema_version=CORPUS_SCHEMA_VERSION,
            canonical_expr=canonical_expr,
            true_coefficients=true_coefficients,
            family_id=family_id,
            operator_signature=_operator_names(tree),
        )
        record = CorpusRecordV1(
            schema_version=CORPUS_SCHEMA_VERSION,
            family_id=family_id,
            corpus_split=config.split_policy.assign(family_id),
            problem=problem,
            oracle=oracle,
        )
        records.append(record)
        seen_family_ids.add(family_id)

    if len(records) < config.num_problems:
        raise ValueError(
            f"generated only {len(records)}/{config.num_problems} problems within {max_attempts} attempts "
            f"({len(rejections)} rejected)"
        )

    frozen_records = tuple(records)
    return SymbolicRegressionCorpusV1(
        schema_version=CORPUS_SCHEMA_VERSION,
        seed=config.seed,
        records=frozen_records,
        rejections=tuple(rejections),
        ood_slices=_build_ood_slices(frozen_records),
        corpus_fingerprint=_corpus_fingerprint(config.seed, frozen_records),
    )


def audit_corpus_leakage(corpus: SymbolicRegressionCorpusV1) -> CorpusLeakageAuditV1:
    """Verify (never assume) that no canonical expression family crosses a
    corpus split and that no family is duplicated -- the empirical leakage
    check backing :func:`generate_corpus`'s split-before-sample invariant."""
    family_to_splits: dict[str, set[str]] = {}
    family_counts: dict[str, int] = {}
    for record in corpus.records:
        family_to_splits.setdefault(record.family_id, set()).add(record.corpus_split)
        family_counts[record.family_id] = family_counts.get(record.family_id, 0) + 1

    cross_split = tuple(sorted(family_id for family_id, splits in family_to_splits.items() if len(splits) > 1))
    duplicates = tuple(sorted(family_id for family_id, count in family_counts.items() if count > 1))
    return CorpusLeakageAuditV1(
        schema_version=CORPUS_SCHEMA_VERSION,
        cross_split_family_violations=cross_split,
        duplicate_family_ids=duplicates,
        is_clean=(not cross_split and not duplicates),
    )


__all__ = [
    "CORPUS_SCHEMA_VERSION",
    "DEFAULT_DOMAIN_POLICY",
    "REJECTION_REASONS",
    "CorpusGenerationConfigV1",
    "CorpusLeakageAuditV1",
    "CorpusOodSlicesV1",
    "CorpusOracleV1",
    "CorpusRecordV1",
    "CorpusRejectionV1",
    "SymbolicRegressionCorpusV1",
    "audit_corpus_leakage",
    "generate_corpus",
]
