"""Supervisor-facing repair composition from typed pending actions and grants."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Literal

from pydantic import Field, field_validator

from slm_training.autoresearch.heal.agent_executor import CodexExecutor
from slm_training.autoresearch.heal.classify import classify_blocker
from slm_training.autoresearch.heal.dispatch import dispatch_repair
from slm_training.autoresearch.heal.isolated_agent import BubblewrapAgentRunner
from slm_training.autoresearch.heal.repair_acceptance import (
    SourceVerificationGate,
    VerificationWorkspace,
    check_manifest_digest,
    verify_repair,
)
from slm_training.autoresearch.heal.repair_contracts import (
    Digest,
    RepairBlocker,
    RepairGrant,
    RepairModel,
    RepairProposal,
    RepairRequest,
)
from slm_training.autoresearch.heal.repair_jobs import (
    bind_verification,
    resumable_proposal,
)
from slm_training.autoresearch.heal.repair_verifier import (
    VerificationCheck,
    VerificationRequest,
)
from slm_training.autoresearch.storage import CampaignStore
from slm_training.harness_core.activity_contract import ResourceGrant
from slm_training.lineage.records import canonical_json


class RepairRecipe(RepairModel):
    """Preapproved original checks and exact files, never generated by the agent."""

    allowed_paths: tuple[str, ...] = Field(min_length=1)
    input_digest: Digest
    original: VerificationCheck
    checks: tuple[VerificationCheck, ...] = Field(min_length=1)
    owner_contract_path: str
    failure_returncode: int = Field(gt=0, lt=256)
    failure_stdout_sha256: Digest
    failure_stderr_sha256: Digest
    semantics_preserving_paths: tuple[str, ...] = ()
    equivalence_checks: tuple[VerificationCheck, ...] = ()


class RecoveryConfig(RepairModel):
    schema_version: Literal["recovery_config/v1"] = "recovery_config/v1"
    grant: RepairGrant | None = None
    source_verification_grant: ResourceGrant | None = None
    recipes: dict[str, RepairRecipe] = Field(default_factory=dict)
    runtime_roots: tuple[str, ...] = ()
    operation_recipes: dict[str, str] = Field(default_factory=dict)
    verifier_release: Digest

    @field_validator("source_verification_grant", mode="before")
    @classmethod
    def strict_source_grant(cls, value):
        return None if value is None else ResourceGrant.model_validate(value, strict=True)

    def proposal_config_digest(self) -> str:
        # New verifier allowance is not a new coding task. Omitting this newly
        # optional field also preserves the pre-extension logical job index.
        value = self.model_dump(mode="json", exclude={"source_verification_grant"})
        return hashlib.sha256(canonical_json(value).encode()).hexdigest()


@dataclass(frozen=True)
class RecoveryContext:
    root: Path
    loop_id: str
    campaign_id: str
    source: Path
    source_digest: str
    environment_digest: str
    fence: str
    parent_event: str
    attempt_id: str = "attempt-0"


def load_recovery_config(path: Path | None) -> RecoveryConfig | None:
    """Only explicit controller-selected config; never infer from CLI/auth/env."""
    if path is None:
        return None
    if path.is_symlink() or path.stat().st_size > 1024 * 1024:
        raise ValueError("invalid recovery config file")
    return RecoveryConfig.model_validate_json(path.read_text(encoding="utf-8"))


def _wait(
    journal: CampaignStore,
    pending: dict,
    context: RecoveryContext,
    reason: str,
    status: str = "waiting_capability",
) -> dict:
    payload = {
        "schema_version": "repair_dispatch_wait/v1",
        "status": status,
        "reason": reason,
        "request_digest": None,
        "blocker_code": pending.get("blocker_code"),
        "loop_id": context.loop_id,
        "fence": context.fence,
        "source_digest": context.source_digest,
        "environment_digest": context.environment_digest,
    }
    artifact = journal.write_artifact("repair_waits", payload)
    events = journal.verify_event_chain()
    if not any(event.get("artifact_sha256") == artifact.stem for event in events):
        journal.append_event(
            "repair_wait", status=status, artifact_sha256=artifact.stem
        )
    return payload


def _read_instruction(source: Path, relative: str) -> str:
    path = source / relative
    if not path.resolve().is_relative_to(source.resolve()) or path.is_symlink():
        raise ValueError("instruction path escapes pinned source")
    if path.stat().st_size > 262144:
        raise ValueError("instruction size exceeds contract")
    return path.read_text(encoding="utf-8")


def build_repair_request(
    pending: dict, context: RecoveryContext, config: RecoveryConfig
) -> RepairRequest:
    """No hand-authored request: resolve the producer code's approved recipe."""
    code = pending.get("blocker_code")
    predicate = pending.get("unmet_predicate")
    capability = pending.get("required_capability")
    if not code or not predicate or not capability:
        raise ValueError("typed_blocker_evidence_missing")
    recipe = config.recipes.get(code)
    if recipe is None:
        raise ValueError("original_reproducer_not_configured")
    instructions = "\n\n".join(
        _read_instruction(context.source, path)
        for path in ("AGENTS.md", "RTK.md", "docs/design/decode-invariants.md")
    )
    owner_contract = _read_instruction(context.source, recipe.owner_contract_path)
    blocker = RepairBlocker(
        code=code,
        blocker_class=classify_blocker(
            str(pending.get("kind", "repair_harness")),
            str(pending.get("reason", "")),
            code=code,
        ),
        owner=str(pending.get("owner") or "improve-openui-harnesses"),
        source_digest=context.source_digest,
        environment_digest=context.environment_digest,
        input_digest=recipe.input_digest,
        reproducer=recipe.original.argv,
        predicate=predicate,
        needed_capability=capability,
        evidence=(str(pending.get("reason") or "typed producer failure")[:512],),
    )
    activity = "repair-" + blocker.fingerprint()
    return RepairRequest(
        blocked_activity_id=pending.get("affected_activity_id"),
        activity_id=activity,
        attempt_id=context.attempt_id,
        campaign_id=context.campaign_id,
        fence=context.fence,
        parent_event=context.parent_event,
        blocker=blocker,
        grant=config.grant,
        allowed_paths=recipe.allowed_paths,
        verification_manifest_digest=check_manifest_digest(
            recipe.original, recipe.checks, recipe.equivalence_checks
        ),
        project_instructions=instructions,
        owner_contract=owner_contract,
        existing_tests=tuple(check.check_id for check in recipe.checks),
        failure_returncode=recipe.failure_returncode,
        failure_stdout_sha256=recipe.failure_stdout_sha256,
        failure_stderr_sha256=recipe.failure_stderr_sha256,
        semantics_preserving_paths=recipe.semantics_preserving_paths,
    )


def dispatch_hard_pending(
    pending: dict,
    context: RecoveryContext,
    *,
    config: RecoveryConfig | None,
    fence_valid: Callable[[str], bool],
    progress: Callable[[], None] = lambda: None,
    cancelled: Callable[[], bool] = lambda: False,
    publish_verified: Callable | None = None,
    source_verification: Callable[[RepairRequest, RepairProposal, VerificationWorkspace], SourceVerificationGate | None] | None = None,
) -> dict:
    """Default production seam; return a durable scoped wait or a real dispatch.

    A later invocation verifies a completed proposal in independent isolated
    workloads; no invocation combines agent time with a second full budget.
    Source publication/acknowledgment remains exclusively controller-owned.
    """
    journal = CampaignStore(context.campaign_id, context.root)
    if not fence_valid(context.fence):
        raise ValueError("stale recovery controller")
    if config is None or config.grant is None:
        return _wait(journal, pending, context, "agent_grant_missing")
    if pending.get("blocker_code") == "controller_operation_failure":
        from .operation_recovery import diagnose_operation

        resolved, reason, probe_ran = diagnose_operation(
            pending, context, config, journal
        )
        if resolved is None or probe_ran:
            needs_diagnosis = resolved is not None or reason in {
                "original_fault_not_reproduced",
                "operation_observation_not_covered_by_recipe",
                "interrupted_diagnosis_requires_reconciliation",
            }
            return _wait(
                journal,
                pending,
                context,
                reason,
                "waiting_diagnosis" if needs_diagnosis else "waiting_capability",
            )
        pending = resolved
    try:
        request = build_repair_request(pending, context, config)
    except (ValueError, OSError) as exc:
        return _wait(
            journal,
            pending,
            context,
            f"repair_input_unavailable:{type(exc).__name__}",
            "waiting_diagnosis",
        )
    # Locate the logical job before comparing attempt/fence identities. Preserve
    # the original request/proposal; only fresh verification authority is rebound.
    request, prior = resumable_proposal(journal, request, config.proposal_config_digest())
    attempt_root = journal.root / "repair_workspaces"
    runner = BubblewrapAgentRunner(
        source=context.source,
        attempt_root=attempt_root,
        runtime_roots=tuple(Path(path) for path in config.runtime_roots),
    )
    executor = CodexExecutor(
        runner,
        instructions=request.project_instructions,
        contract=request.owner_contract,
    )
    result = prior or dispatch_repair(
        request,
        executor=executor,
        journal=journal,
        fence_valid=fence_valid,
        progress=progress,
        cancelled=cancelled,
    )
    workspace = VerificationWorkspace(
        context.source, attempt_root / request.digest() / "candidate", runner.runtime_roots
    )
    # The factory only resolves controller-owned materialization/journal inputs.
    # It must not execute the full verification queue inside this repair attempt.
    source_gate = (
        source_verification(request, result.proposal, workspace)
        if source_verification and result.status == "waiting_verification" and result.proposal
        else None
    )
    if (
        prior is not None
        and result.status == "waiting_verification"
        and result.proposal is not None
    ):
        recipe = config.recipes[request.blocker.code]
        binding = bind_verification(journal, request, result.proposal, context)
        verify_request = VerificationRequest(
            request.digest(),
            request.blocker.fingerprint(),
            request.blocker.source_digest,
            result.proposal.tree_digest,
            request.blocker.environment_digest,
            config.verifier_release,
            config.grant.digest(),
            binding.fence,
            request.allowed_paths,
            recipe.original,
            recipe.checks,
            recipe.failure_returncode,
            recipe.failure_stdout_sha256,
            recipe.failure_stderr_sha256,
            timeout_seconds=config.grant.interrupt_seconds,
            semantics_preserving_paths=recipe.semantics_preserving_paths,
            equivalence_checks=recipe.equivalence_checks,
        )
        result = verify_repair(
            request,
            result.proposal,
            verify_request,
            workspace=workspace,
            journal=journal,
            fence_valid=fence_valid,
            binding=binding,
            source_verification=source_gate,
        )
    response = result.model_dump(mode="json")
    if result.status == "waiting_verification" and result.proposal is not None:
        dependency = _verification_dependency(
            request, result.proposal, source_gate, config.source_verification_grant
        )
        artifact = journal.write_artifact("repair_verification_dependencies", dependency)
        journal.append_event(
            "repair_verification_dependency", artifact_sha256=artifact.stem,
            idempotency_key="repair-verification-dependency:" + artifact.stem,
            detail=dependency,
        )
        response["verification_dependency"] = dependency
    if result.status == "verified" and publish_verified is not None:
        # This callback belongs to the trusted controller, not the worker grant.
        response["release_handoff"] = publish_verified(
            request, result, attempt_root / request.digest() / "candidate"
        )
    return response


def _verification_dependency(request, proposal, gate: SourceVerificationGate | None, grant=None):
    """Parent enqueues a separately granted verify activity, then parks this repair.

    Wake only after authenticating complete evidence for this exact identity.
    YIELD/retry alone is not this dependency's producer and can exhaust a repair
    while thousands of independent verification nodes remain pending.
    """
    gate = gate if grant is not None else None
    identity = gate.identity if gate else request.verification_manifest_digest
    return {
        "schema_version": "repair_verification_dependency/v1",
        "kind": "verify", "activity_id": "source-verification-" + identity if gate else None,
        "request_digest": request.digest(), "proposal_digest": proposal.digest(),
        "campaign_id": request.campaign_id, "blocked_activity_id": request.blocked_activity_id,
        "source_snapshot_digest": request.blocker.source_digest,
        "candidate_snapshot_digest": proposal.tree_digest,
        "verification_identity": gate.identity if gate else None,
        "root": str(gate.root.resolve()) if gate else None,
        "state_dir": str(gate.state_dir.resolve()) if gate else None,
        "base_ref": gate.base_ref if gate else None,
        "manifest_path": str(gate.root.parent / "manifest.json") if gate else None,
        "grant": grant.model_dump(mode="json") if grant is not None else None,
        "required_capability": "isolated_source_verifier",
        "grant_required": True,
        "wake": {
            "predicate": "complete_current_source_verification" if gate else "source_verifier_configured",
            "source": "source_verification_completed" if gate else "controller_policy",
            "identity_digest": identity,
        },
    }
