"""Repo-owned source discovery for the code-quality gate.

Static only -- shells out to ``git ls-files`` and reads text, so it runs in the
dependency-light static CI job (``.github/workflows/ci.yml`` ``python-static``).

"Repo-owned" excludes build output and vendored trees, because a quality budget
levied on generated bytes measures the generator, not the codebase. See
``docs/design/code-quality-contract.md``.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]

#: Physical-line budget for a single module. Robert C. Martin's "Clean Code"
#: argues for far smaller files still; 400 is the repository's enforced ceiling.
MAX_MODULE_LINES = 400

#: Extensions carrying hand-written logic subject to the budget.
SOURCE_SUFFIXES: dict[str, str] = {
    ".py": "python",
    ".ts": "typescript",
    ".tsx": "typescript",
}

#: Trees that are build output or vendored third-party code. Every entry is a
#: repo-relative path prefix.
#:
#: ``src/slm_training/web/static`` is emitted by ``npm run preview:build`` and
#: ``npm run dashboard:build`` from ``src/apps/*``; the checked-in bundles there
#: (``preview.js`` alone is 98k minified lines) are artifacts, not source.
EXCLUDED_PREFIXES: tuple[str, ...] = (
    "src/slm_training/web/static/",
    "node_modules/",
    "src/apps/dashboard/node_modules/",
    "src/apps/openui_preview/node_modules/",
    "src/apps/dashboard/dist/",
    "src/apps/openui_preview/dist/",
)

#: Never repo-owned source. ``git ls-files`` already omits these, but the
#: filesystem fallback below does not, and a baseline that had swept ``.venv``
#: would be nonsense -- tens of thousands of third-party modules recorded as
#: this repository's debt.
NON_SOURCE_PREFIXES: tuple[str, ...] = (
    ".venv/",
    "venv/",
    ".git/",
    ".mypy_cache/",
    ".pytest_cache/",
    ".ruff_cache/",
    "__pycache__/",
    "outputs/",
    "build/",
    "dist/",
)

#: Vendored agent-skill mirrors, refreshed by ``hf skills update`` rather than
#: edited here. Kept in sync with ``[tool.ruff] extend-exclude`` in pyproject.
VENDORED_SKILL_PREFIXES: tuple[str, ...] = (
    ".agents/skills/",
    ".claude/skills/",
    ".cursor/skills/",
    ".grok/skills/",
    ".codex/skills/",
)

#: Markers that mark a file as machine-emitted regardless of where it lives.
GENERATED_MARKERS: tuple[str, ...] = (
    "@generated",
    "Code generated by",
    "DO NOT EDIT",
    "autogenerated by",
)


_ALL_EXCLUDED: tuple[str, ...] = (
    EXCLUDED_PREFIXES + VENDORED_SKILL_PREFIXES + NON_SOURCE_PREFIXES
)

#: Directory names excluded wherever they appear in a path, not only at the root.
_NESTED_EXCLUDED: tuple[str, ...] = ("__pycache__/", "node_modules/", ".venv/")


@dataclass(frozen=True)
class SourceFile:
    """One repo-owned source file and its physical line count."""

    path: str
    lines: int
    language: str

    @property
    def over_budget(self) -> bool:
        return self.lines > MAX_MODULE_LINES


def _tracked_paths(*, root: Path) -> list[str]:
    """Every tracked *and* new-but-not-ignored path.

    ``--others --exclude-standard`` adds files that exist on disk but are not
    committed yet, so a newly written oversized module fails the gate while it
    is still being written rather than one commit later.
    """

    try:
        out = subprocess.run(
            ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return sorted(
            p.relative_to(root).as_posix()
            for p in root.rglob("*")
            if p.is_file()
        )
    return [entry for entry in out.split("\0") if entry]


def is_excluded(path: str) -> bool:
    """True when ``path`` is build output or a vendored mirror."""

    if path.startswith(_ALL_EXCLUDED):
        return True
    # `__pycache__` and friends also appear nested, not just at the root.
    return any(f"/{segment}" in f"/{path}" for segment in _NESTED_EXCLUDED)


def is_generated(text: str) -> bool:
    """True when the file header marks it as machine-emitted."""

    header = "\n".join(text.splitlines()[:5])
    return any(marker in header for marker in GENERATED_MARKERS)


def discover(*, root: Path = ROOT) -> list[SourceFile]:
    """Every repo-owned source file, sorted by path.

    Skips build output, vendored mirrors, generated headers, and files that are
    not valid UTF-8 (binary blobs committed with a source suffix).
    """

    found: list[SourceFile] = []
    for rel in _tracked_paths(root=root):
        language = SOURCE_SUFFIXES.get(Path(rel).suffix)
        if language is None or is_excluded(rel):
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if is_generated(text):
            continue
        found.append(
            SourceFile(path=rel, lines=len(text.splitlines()), language=language)
        )
    return sorted(found, key=lambda item: item.path)


def over_budget(files: list[SourceFile]) -> list[SourceFile]:
    """The files exceeding :data:`MAX_MODULE_LINES`, largest first."""

    return sorted(
        (item for item in files if item.over_budget),
        key=lambda item: (-item.lines, item.path),
    )
