"""reasoning/revmath typed contracts + deterministic runner (HARN-02..11).

Schemas: HARN-02. Runner / replay / report: HARN-03.
Assumption ablation: HARN-04. Reversal / bidirectional: HARN-05.
Constructivization + computable/finite counterexample: HARN-06.
Quantitative-bound extraction: HARN-07.
Conservative RM labeling / anti-overclaim: HARN-08.
Proposition-preserving self-healing: HARN-09.
Campaign locking / profile CLI: HARN-10.
Frozen fixture corpus: HARN-11.
Failure/repair witness routing: INTEG-05.
"""

from __future__ import annotations

from slm_training.harnesses.reasoning.revmath.corpus import (
    CORPUS_ID,
    CORPUS_SCHEMA,
    REQUIRED_CORPUS_CLASSES,
    FixtureCorpusEntryV1,
    FixtureCorpusManifestV1,
    assert_no_undeclared_train_eval_leakage,
    build_fixture_corpus_manifest,
    coverage_table,
    demonstrate_mutation_failures,
    detect_train_eval_leakage,
    load_fixture_corpus_manifest,
    verify_corpus_replay,
)
from slm_training.harnesses.reasoning.revmath.profile_binding import (
    RevmathCampaignBindingError,
    RevmathProfilePlanV1,
    RevmathProfileRunV1,
    assert_tasks_match_lock,
    bind_tasks_to_lock,
    materialize_fixture_campaign,
    replay_profile_run_from_store,
    require_locked_campaign,
    run_revmath_profile,
)
from slm_training.harnesses.reasoning.revmath.assumption_ablation import (
    MINIMALITY_CLAIM_SCOPE,
    AblationCandidateV1,
    AblationMetaV1,
    AblationSearchReportV1,
    audit_hidden_reintroduction,
    evaluate_ablation_lattice,
    generate_ablation_candidates,
    materialize_candidate_task,
    parse_ablation_meta,
)
from slm_training.harnesses.reasoning.revmath.constructivization import (
    ConstructivizationMetaV1,
    ConstructivizationReportV1,
    ConstructivizationVariantV1,
    assert_not_masquerading,
    evaluate_constructivization,
    generate_constructivization_variant,
    materialize_constructivized_task,
    parse_constructivization_meta,
)
from slm_training.harnesses.reasoning.revmath.counterexample import (
    CounterexampleMetaV1,
    CounterexampleModelV1,
    CounterexampleReportV1,
    build_counterexample_model,
    check_counterexample_against_theorem,
    evaluate_counterexample,
    parse_counterexample_meta,
)
from slm_training.harnesses.reasoning.revmath.labeling import (
    INSUFFICIENT_FOR_BIG_FIVE,
    AnalysisKind,
    EvidenceKind,
    RmLabelClaimV1,
    RmLabelingState,
    RmLabelVerdictV1,
    anti_overclaim_reasons,
    assert_label_claim_accepted,
    default_analysis_kind_for_task,
    has_big_five_equivalence_package,
    parse_label_claim,
    report_labeling_disclaimer,
    validate_label_claim,
)
from slm_training.harnesses.reasoning.revmath.plugins import (
    AssumptionAblationPlugin,
    ConstructivizationPlugin,
    CounterexamplePlugin,
    HermeticForwardPlugin,
    PluginCheckEvidence,
    QuantitativeBoundPlugin,
    ReversalPlugin,
    RevmathCheckPlan,
    RevmathTaskPlugin,
    default_plugin_registry,
    resolve_plugin,
)
from slm_training.harnesses.reasoning.revmath.quantitative_bound import (
    QuantitativeBoundMetaV1,
    QuantitativeBoundReportV1,
    extract_quantitative_bound,
    parse_quantitative_bound_meta,
)
from slm_training.harnesses.reasoning.revmath.replay import (
    assert_revmath_replay_integrity,
    build_revmath_replay_bundle,
)
from slm_training.harnesses.reasoning.revmath.report import (
    build_revmath_report,
    labeling_notes_for_tasks,
)
from slm_training.harnesses.reasoning.revmath.reversal import (
    ReversalMetaV1,
    ReversalObligationV1,
    ReversalReportV1,
    evaluate_reversal,
    generate_reversal_obligations,
    materialize_obligation_task,
    parse_reversal_meta,
)
from slm_training.harnesses.reasoning.revmath.runner import (
    RevmathRunRecord,
    run_revmath_task,
)
from slm_training.harnesses.reasoning.revmath.schemas import (
    REVMATH_MUTABLE_REPAIR_KNOBS,
    REVMATH_SCHEMA_VERSIONS,
    AxisCertificateRefV1,
    RevmathBaseTheoryV1,
    RevmathBudgetV1,
    RevmathCampaignBindingV1,
    RevmathCorpusEntryV1,
    RevmathCorpusIdentityV1,
    RevmathFourAxisAnalysisV1,
    RevmathProofArtifactRefV1,
    RevmathPropositionIdentityV1,
    RevmathRepairKnobChangeV1,
    RevmathRepairRecordV1,
    RevmathReportV1,
    RevmathResultV1,
    RevmathSchemaError,
    RevmathTaskKind,
    RevmathTaskV1,
    RevmathVerifierJudgeIdentityV1,
    TheoremDirection,
    assert_repair_preserves_identity,
    canonical_hash,
    export_json_schemas,
    parse_revmath_corpus_entry,
    parse_revmath_repair,
    parse_revmath_report,
    parse_revmath_result,
    parse_revmath_task,
)
from slm_training.harnesses.reasoning.revmath.self_healing import (
    DEFAULT_MAX_ATTEMPTS,
    REVMATH_FROZEN_REPAIR_FIELDS,
    RevmathRepairAttemptV1,
    RevmathRepairKnobStateV1,
    RevmathRepairProposalV1,
    RevmathRepairSessionV1,
    assert_serialized_repair_freeze,
    build_repair_record,
    equivalent_repair_signature,
    propose_repair_attempts,
    reject_forbidden_repair,
    run_self_healing,
    semantic_repair_lineage_from_session,
)

from slm_training.harnesses.reasoning.revmath.failure_witness import (
    REVMATH_FAILURE_TAXONOMY_VERSION,
    BoundedRepairActionV1,
    RevmathFailureClass,
    RevmathFailureEvidenceV1,
    bounded_repair_actions_for,
    feed_repair_session_to_disposition,
    route_revmath_failure,
)

__all__ = [
    "REVMATH_FAILURE_TAXONOMY_VERSION",
    "BoundedRepairActionV1",
    "RevmathFailureClass",
    "RevmathFailureEvidenceV1",
    "bounded_repair_actions_for",
    "feed_repair_session_to_disposition",
    "route_revmath_failure",

    "AblationCandidateV1",
    "AblationMetaV1",
    "AblationSearchReportV1",
    "AnalysisKind",
    "AssumptionAblationPlugin",
    "AxisCertificateRefV1",
    "CORPUS_ID",
    "CORPUS_SCHEMA",
    "ConstructivizationMetaV1",
    "ConstructivizationPlugin",
    "ConstructivizationReportV1",
    "ConstructivizationVariantV1",
    "CounterexampleMetaV1",
    "CounterexampleModelV1",
    "CounterexamplePlugin",
    "CounterexampleReportV1",
    "DEFAULT_MAX_ATTEMPTS",
    "EvidenceKind",
    "FixtureCorpusEntryV1",
    "FixtureCorpusManifestV1",
    "HermeticForwardPlugin",
    "INSUFFICIENT_FOR_BIG_FIVE",
    "MINIMALITY_CLAIM_SCOPE",
    "PluginCheckEvidence",
    "QuantitativeBoundMetaV1",
    "QuantitativeBoundPlugin",
    "QuantitativeBoundReportV1",
    "REQUIRED_CORPUS_CLASSES",
    "REVMATH_FROZEN_REPAIR_FIELDS",
    "REVMATH_MUTABLE_REPAIR_KNOBS",
    "REVMATH_SCHEMA_VERSIONS",
    "ReversalMetaV1",
    "ReversalObligationV1",
    "ReversalPlugin",
    "ReversalReportV1",
    "RevmathBaseTheoryV1",
    "RevmathBudgetV1",
    "RevmathCampaignBindingError",
    "RevmathCampaignBindingV1",
    "RevmathCheckPlan",
    "RevmathCorpusEntryV1",
    "RevmathCorpusIdentityV1",
    "RevmathFourAxisAnalysisV1",
    "RevmathProfilePlanV1",
    "RevmathProfileRunV1",
    "RevmathProofArtifactRefV1",
    "RevmathPropositionIdentityV1",
    "RevmathRepairAttemptV1",
    "RevmathRepairKnobChangeV1",
    "RevmathRepairKnobStateV1",
    "RevmathRepairProposalV1",
    "RevmathRepairRecordV1",
    "RevmathRepairSessionV1",
    "RevmathReportV1",
    "RevmathResultV1",
    "RevmathRunRecord",
    "RevmathSchemaError",
    "RevmathTaskKind",
    "RevmathTaskPlugin",
    "RevmathTaskV1",
    "RevmathVerifierJudgeIdentityV1",
    "RmLabelClaimV1",
    "RmLabelVerdictV1",
    "RmLabelingState",
    "TheoremDirection",
    "anti_overclaim_reasons",
    "assert_label_claim_accepted",
    "assert_no_undeclared_train_eval_leakage",
    "assert_not_masquerading",
    "assert_repair_preserves_identity",
    "assert_revmath_replay_integrity",
    "assert_serialized_repair_freeze",
    "assert_tasks_match_lock",
    "audit_hidden_reintroduction",
    "bind_tasks_to_lock",
    "build_counterexample_model",
    "build_fixture_corpus_manifest",
    "build_repair_record",
    "build_revmath_replay_bundle",
    "build_revmath_report",
    "canonical_hash",
    "check_counterexample_against_theorem",
    "coverage_table",
    "default_analysis_kind_for_task",
    "default_plugin_registry",
    "demonstrate_mutation_failures",
    "detect_train_eval_leakage",
    "equivalent_repair_signature",
    "evaluate_ablation_lattice",
    "evaluate_constructivization",
    "evaluate_counterexample",
    "evaluate_reversal",
    "export_json_schemas",
    "extract_quantitative_bound",
    "generate_ablation_candidates",
    "generate_constructivization_variant",
    "generate_reversal_obligations",
    "has_big_five_equivalence_package",
    "labeling_notes_for_tasks",
    "load_fixture_corpus_manifest",
    "materialize_candidate_task",
    "materialize_constructivized_task",
    "materialize_fixture_campaign",
    "materialize_obligation_task",
    "parse_ablation_meta",
    "parse_constructivization_meta",
    "parse_counterexample_meta",
    "parse_label_claim",
    "parse_quantitative_bound_meta",
    "parse_reversal_meta",
    "parse_revmath_corpus_entry",
    "parse_revmath_repair",
    "parse_revmath_report",
    "parse_revmath_result",
    "parse_revmath_task",
    "propose_repair_attempts",
    "reject_forbidden_repair",
    "replay_profile_run_from_store",
    "report_labeling_disclaimer",
    "require_locked_campaign",
    "resolve_plugin",
    "run_revmath_profile",
    "run_revmath_task",
    "run_self_healing",
    "semantic_repair_lineage_from_session",
    "validate_label_claim",
    "verify_corpus_replay",
]
