"""reasoning/revmath typed contracts + deterministic runner (HARN-02..07).

Schemas: HARN-02. Runner / replay / report: HARN-03.
Assumption ablation: HARN-04. Reversal / bidirectional: HARN-05.
Constructivization + computable/finite counterexample: HARN-06.
Quantitative-bound extraction: HARN-07.
"""

from __future__ import annotations

from slm_training.harnesses.reasoning.revmath.quantitative_bound import (
    QuantitativeBoundMetaV1,
    QuantitativeBoundReportV1,
    extract_quantitative_bound,
    parse_quantitative_bound_meta,
)
from slm_training.harnesses.reasoning.revmath.constructivization import (
    ConstructivizationMetaV1,
    ConstructivizationReportV1,
    ConstructivizationVariantV1,
    assert_not_masquerading,
    evaluate_constructivization,
    generate_constructivization_variant,
    materialize_constructivized_task,
    parse_constructivization_meta,
)
from slm_training.harnesses.reasoning.revmath.counterexample import (
    CounterexampleMetaV1,
    CounterexampleModelV1,
    CounterexampleReportV1,
    build_counterexample_model,
    check_counterexample_against_theorem,
    evaluate_counterexample,
    parse_counterexample_meta,
)
from slm_training.harnesses.reasoning.revmath.reversal import (
    ReversalMetaV1,
    ReversalObligationV1,
    ReversalReportV1,
    evaluate_reversal,
    generate_reversal_obligations,
    materialize_obligation_task,
    parse_reversal_meta,
)
from slm_training.harnesses.reasoning.revmath.assumption_ablation import (
    MINIMALITY_CLAIM_SCOPE,
    AblationCandidateV1,
    AblationMetaV1,
    AblationSearchReportV1,
    audit_hidden_reintroduction,
    evaluate_ablation_lattice,
    generate_ablation_candidates,
    materialize_candidate_task,
    parse_ablation_meta,
)
from slm_training.harnesses.reasoning.revmath.plugins import (
    AssumptionAblationPlugin,
    HermeticForwardPlugin,
    ReversalPlugin,
    QuantitativeBoundPlugin,
    ConstructivizationPlugin,
    CounterexamplePlugin,
    PluginCheckEvidence,
    RevmathCheckPlan,
    RevmathTaskPlugin,
    default_plugin_registry,
    resolve_plugin,
)
from slm_training.harnesses.reasoning.revmath.report import build_revmath_report
from slm_training.harnesses.reasoning.revmath.replay import (
    assert_revmath_replay_integrity,
    build_revmath_replay_bundle,
)
from slm_training.harnesses.reasoning.revmath.runner import RevmathRunRecord, run_revmath_task
from slm_training.harnesses.reasoning.revmath.schemas import (
    REVMATH_MUTABLE_REPAIR_KNOBS,
    REVMATH_SCHEMA_VERSIONS,
    AxisCertificateRefV1,
    RevmathBaseTheoryV1,
    RevmathBudgetV1,
    RevmathCampaignBindingV1,
    RevmathCorpusEntryV1,
    RevmathCorpusIdentityV1,
    RevmathFourAxisAnalysisV1,
    RevmathProofArtifactRefV1,
    RevmathPropositionIdentityV1,
    RevmathRepairKnobChangeV1,
    RevmathRepairRecordV1,
    RevmathReportV1,
    RevmathResultV1,
    RevmathSchemaError,
    RevmathTaskKind,
    RevmathTaskV1,
    RevmathVerifierJudgeIdentityV1,
    TheoremDirection,
    assert_repair_preserves_identity,
    canonical_hash,
    export_json_schemas,
    parse_revmath_corpus_entry,
    parse_revmath_repair,
    parse_revmath_report,
    parse_revmath_result,
    parse_revmath_task,
)

__all__ = [
    "REVMATH_MUTABLE_REPAIR_KNOBS",
    "REVMATH_SCHEMA_VERSIONS",
    "AxisCertificateRefV1",
    "AssumptionAblationPlugin",
    "parse_counterexample_meta",
    "parse_constructivization_meta",
    "materialize_constructivized_task",
    "generate_constructivization_variant",
    "evaluate_counterexample",
    "evaluate_constructivization",
    "check_counterexample_against_theorem",
    "build_counterexample_model",
    "assert_not_masquerading",
    "CounterexampleReportV1",
    "CounterexampleModelV1",
    "CounterexampleMetaV1",
    "CounterexamplePlugin",
    "ConstructivizationVariantV1",
    "ConstructivizationReportV1",
    "ConstructivizationMetaV1",
    "ConstructivizationPlugin",
    "evaluate_reversal",
    "generate_reversal_obligations",
    "materialize_obligation_task",
    "parse_reversal_meta",
    "parse_quantitative_bound_meta",
    "extract_quantitative_bound",
    "QuantitativeBoundReportV1",
    "QuantitativeBoundMetaV1",
    "ReversalObligationV1",
    "ReversalMetaV1",
    "ReversalReportV1",
    "ReversalPlugin",
    "QuantitativeBoundPlugin",
    "HermeticForwardPlugin",
    "parse_ablation_meta",
    "materialize_candidate_task",
    "generate_ablation_candidates",
    "evaluate_ablation_lattice",
    "audit_hidden_reintroduction",
    "AblationSearchReportV1",
    "AblationMetaV1",
    "AblationCandidateV1",
    "MINIMALITY_CLAIM_SCOPE",
    "PluginCheckEvidence",
    "RevmathBaseTheoryV1",
    "RevmathBudgetV1",
    "RevmathCampaignBindingV1",
    "RevmathCheckPlan",
    "RevmathCorpusEntryV1",
    "RevmathCorpusIdentityV1",
    "RevmathFourAxisAnalysisV1",
    "RevmathProofArtifactRefV1",
    "RevmathPropositionIdentityV1",
    "RevmathRepairKnobChangeV1",
    "RevmathRepairRecordV1",
    "RevmathReportV1",
    "RevmathResultV1",
    "RevmathRunRecord",
    "RevmathSchemaError",
    "RevmathTaskKind",
    "RevmathTaskPlugin",
    "RevmathTaskV1",
    "RevmathVerifierJudgeIdentityV1",
    "TheoremDirection",
    "assert_repair_preserves_identity",
    "assert_revmath_replay_integrity",
    "build_revmath_replay_bundle",
    "build_revmath_report",
    "canonical_hash",
    "default_plugin_registry",
    "export_json_schemas",
    "parse_revmath_corpus_entry",
    "parse_revmath_repair",
    "parse_revmath_report",
    "parse_revmath_result",
    "parse_revmath_task",
    "resolve_plugin",
    "run_revmath_task",
]
