"""Torch-free finite-domain support-lattice primitives."""

from slm_training.dsl.solver.adapters import (
    TopologyDomainAdapter,
    completion_forest_state,
)
from slm_training.dsl.solver.state import (
    DomainValue,
    FiniteDomainState,
    HoleDomain,
    HoleId,
    JsonScalar,
    SolverBounds,
    SupportVerdict,
)
from slm_training.dsl.solver.closure import (
    CertifiedDeduction,
    ClosureCounters,
    ClosureResult,
    EnumerativeSupportProvider,
    SupportProvider,
    WitnessRef,
    default_query_order,
    exact_closure,
)
from slm_training.dsl.solver.support import (
    EnumerativeSupportOracle,
    ExpandStatus,
    ExpandStep,
    ProblemExpander,
    ReplayResult,
    SearchCounters,
    SupportCertificate,
    SupportOracle,
    SupportQuery,
    SupportResult,
    VerifyOutcome,
    VerifyStatus,
    Verifier,
    replay_support_certificate,
)

__all__ = [
    "CertifiedDeduction",
    "ClosureCounters",
    "ClosureResult",
    "DomainValue",
    "EnumerativeSupportOracle",
    "EnumerativeSupportProvider",
    "ExpandStatus",
    "ExpandStep",
    "FiniteDomainState",
    "HoleDomain",
    "HoleId",
    "JsonScalar",
    "ProblemExpander",
    "ReplayResult",
    "SearchCounters",
    "SolverBounds",
    "SupportCertificate",
    "SupportOracle",
    "SupportProvider",
    "SupportQuery",
    "SupportResult",
    "SupportVerdict",
    "TopologyDomainAdapter",
    "Verifier",
    "VerifyOutcome",
    "VerifyStatus",
    "WitnessRef",
    "completion_forest_state",
    "default_query_order",
    "exact_closure",
    "replay_support_certificate",
]
