"""Torch-free finite-domain support-lattice primitives."""

from slm_training.dsl.solver.adapters import (
    TopologyDomainAdapter,
    completion_forest_state,
)
from slm_training.dsl.solver.state import (
    DomainValue,
    FiniteDomainState,
    HoleDomain,
    HoleId,
    JsonScalar,
    SolverBounds,
    SupportVerdict,
)
from slm_training.dsl.solver.support import (
    REFERENCE_SEARCH_ORDER,
    SUPPORT_CERTIFICATE_SCHEMA_VERSION,
    CompletionForestExpander,
    EnumerativeSupportOracle,
    Expansion,
    ExpansionEdge,
    ReplayResult,
    SearchCounters,
    SupportCertificate,
    SupportDecoder,
    SupportExpander,
    SupportOracle,
    SupportQuery,
    SupportResult,
    SupportVerifier,
    VerifierOutcome,
    get_support_backend,
    make_completion_forest_expander,
    make_pack_verifier,
    make_token_decoder,
    register_support_backend,
    replay_support_certificate,
    support_backends,
)

__all__ = [
    "REFERENCE_SEARCH_ORDER",
    "SUPPORT_CERTIFICATE_SCHEMA_VERSION",
    "CompletionForestExpander",
    "DomainValue",
    "EnumerativeSupportOracle",
    "Expansion",
    "ExpansionEdge",
    "FiniteDomainState",
    "HoleDomain",
    "HoleId",
    "JsonScalar",
    "ReplayResult",
    "SearchCounters",
    "SolverBounds",
    "SupportCertificate",
    "SupportDecoder",
    "SupportExpander",
    "SupportOracle",
    "SupportQuery",
    "SupportResult",
    "SupportVerdict",
    "SupportVerifier",
    "TopologyDomainAdapter",
    "VerifierOutcome",
    "completion_forest_state",
    "get_support_backend",
    "make_completion_forest_expander",
    "make_pack_verifier",
    "make_token_decoder",
    "register_support_backend",
    "replay_support_certificate",
    "support_backends",
]
